name: minimal
channels:
- conda-forge
- anaconda
dependencies:
- python=3.11
- pip=24.0
- pip:
  - azureml-inference-server-http==1.3.0
  - numpy==1.23.5
  - sentencepiece==0.2.0
  - torch==2.4.0
  - diffusers==0.30.1
  - transformers==4.44.2
  - accelerate==0.33.0
  - azure-ai-ml==1.16.1 
  - azureml-ai-monitoring==1.0.0 
  - azureml-core==1.56.0